config/routes.rb
Offerr::Application.routes.draw do

  resources :items
  
  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :title, :value, :description, :location, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_item, only: [:show, :edit, :update, :destroy]

	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)

		if @item.save
			flash[:notice] = "Item has been created."
			redirect_to @item
		else
			flash[:alert] = "Project has not been created."

			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @item.update(item_params)
			flash[:notice] = "Item has been updated."
			redirect_to @item
		else
			flash[:alert] = "Item has not been updated."
			render "edit"
		end
	end

	def destroy
		@item.destroy

		flash[:notice] = "Item has been destroyed."

		redirect_to items_path

	end

	private
		def item_params
			params.require(:item).permit(:title, :value, :description, :location)
		end

		def set_item
			@item = Item.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			flash[:alert] = "The item you were looking for could not be found."
			redirect_to items_path
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
				(parts << "Offerr").join(" - ")
			end
		end
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
	<% if @item.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

			<ul>
				<%= @item.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :value %><br />
		<%= f.text_field :value %>
	</p>
	<p>
		<%= f.label :description %><br />
		<%= f.text_field :description %>
	</p>
	<p>
		<%= f.label :location %><br />
		<%= f.text_field :location %>
	</p>
	<%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h2> Edit item </h2>

<%= render "form" %>

app/views/items/index.html.erb
<%= link_to 'New Item', new_item_path %>

<h2>Items</h2>
	<ul>
		<% @items.each do |item| %>
			<li><%= link_to item.title, item %></li>
		<% end %>
	</ul>
	

app/views/items/new.html.erb
<h1> New Project </h1>

<%= render "form" %>

app/views/items/show.html.erb
<%	title(@item.title, "Items") %>
<h2> <%= @item.title %></h2>
<%= link_to "Edit Item", edit_item_path(@item) %>
<%= link_to "Delete Item", item_path(@item), method: :delete, data: { confirm: "Are you sure you want to delete this item?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if content_for?(:title) %>
  		<%= yield(:title) %>
  	<% else %>
  		Offerr
  	<% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
		<%= value %>
	</div>
<% end %>

<%= yield %>

</body>
</html>